# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 96f19ccf3307eb5f5fd5df7898edaf790109704f1c2b3aad0fda59c301afc10c30c0490096231688ee560c178eb660ba8f72b92b788c4656d273c821933b7b98

test:
  secret_key_base: 5b011c0ad22f2b824001dba48d00979fa3c84860a22e0e4499e38c40825268e065cab31cb973f1524cf7e34f4cb0e81d48fb47de35af091c44ab03df1f888d24

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
